Home works
SerhiiYatsyn/GeekHub pull request #3
Opened 2018-10-20 14:24 UTC by SerhiiYatsyn

2018-10-20 22:42 UTC, SerhiiYatsyn commented
![image](https://user-images.githubusercontent.com/44030464/47261180-82f33e00-d4d2-11e8-9a7e-beeaa6a2587c.png)
![image](https://user-images.githubusercontent.com/44030464/47261188-90a8c380-d4d2-11e8-9f90-84f98e32e964.png)
![image](https://user-images.githubusercontent.com/44030464/47261189-9d2d1c00-d4d2-11e8-846b-2d45ac7cd7aa.png)

2018-10-21 19:44 UTC, spolischook requested changes
I've suggest use ```div``` as wrapper for form fields instead of ```p```, however Yana suggest use ```li``` and I'm agree, because it's semantically right

```id``` attribute is required for field in case if label has ```for``` attribute https://www.w3schools.com/tags/att_for.asp

I've suggest use ```div``` as wrapper for form fields instead of ```p```, however Yana suggest use ```li``` and I'm agree, because it's semantically right

2018-10-21 19:44 UTC, spolischook commented on HW2/form.html
> +	        	<input type="text" name="id" disabled value="725" size="50">
```readonly``` or ```disabled``` attribute should be applied

2018-10-21 19:44 UTC, spolischook commented on HW2/form.html
> +	        	<input type="text" name="firstname" maxlength="25" size="50">
id attribute is missed

2018-10-21 19:44 UTC, spolischook commented on HW2/form.html
> +	        	Skills<br>
duplicated and meaningless values for checkboxes

2018-10-21 19:44 UTC, spolischook commented on HW2/form.html
> +		            <option value="UK"> Ukraine</option>
Ukraine is UA not UK

2018-10-21 19:44 UTC, spolischook commented on HW2/form.html
> +	        	<select name="yourCountry">
Preferred choices is missed. See wire-frame

2018-11-04 13:34 UTC, closed without merging